### ISSUE TITLE
Repospanner nodes not capable of recovering from failed join

### ISSUE THREAD

**Issue by bkabrda** [repoSpanner/repoSpanner#32]
I'm trying to run 3 repospanner nodes in a container environment. All 3 nodes are started pretty much at the same time (as are all other containers of my Pagure setup). Node 1 calls "spawn" and then starts serving, nodes 2 and 3 are supposed to join node 1.
The problem is that when starting for the first time, nodes 2 and 3 try to join, node 1 is usually not finished with the spawning yet and so it's not up. This makes nodes 2 and 3 fail, but they still create "async-outqueues", "objectsyncs" and "repoinfos" (empty) directories before failing; state.json is not created in this scenario. These directories are on a persistent volume, so they stay there between restarts. When OpenShift tries to restart nodes 2 and 3, they subsequently fail with `level=fatal msg="Fatal error occured" error="mkdir /var/lib/repospanner/state/async-outqueues: file exists"`. I see 3 ways to solve this:
* don't try to create these directories if they exist
* remove these directories if initialization fails
* create an empty state.json so that initialization is not attempted on subsequent restarts
I don't understand repospanner good enough to be able to say which of these is correct, so I'm just laying these options out.

**Comment by puiterwijk** [comment]
Note that this stopped becoming a critical failure as of 1172930464fd055e958dc14b98d7c640d97fadac, but joining while a node is still spawning is going to result in many hard to track bugs due to the Raft state.
As a result, 0299eabb56f72bd5b4e7317bbeec76d93b348f5e makes it so the RPC port doesn't get opened while spawning, which means that joining nodes can't get into an inconsistent state.

**Comment by puiterwijk** [comment]
Note that this stopped becoming a critical failure as of 1172930464fd055e958dc14b98d7c640d97fadac, but joining while a node is still spawning is going to result in many hard to track bugs due to the Raft state.
As a result, 0299eabb56f72bd5b4e7317bbeec76d93b348f5e makes it so the RPC port doesn't get opened while spawning, which means that joining nodes can't get into an inconsistent state.
