### ISSUE TITLE
RFE: make repobridge config file use viper

### ISSUE THREAD

**Issue by bkabrda** [repoSpanner/repoSpanner#34]
While running repoSpanner on several different environments with mostly the same config, I'm utilizing viper's feature where you can provide both a configuration file (which would contain values that are common to all environments) and environment variables (through which you can provide values that are different for each environment). So for example I have a config file that contains `ca.path`, but it doesn't contain `admin.url` - I have an environment variable `REPOSPANNER_ADMIN.URL` for that.

I'd like to have a similar setup for repobridge config, where it would be mostly the same, but I would provide `REPOBRIDGE_BASEURL` as an environment variable. Right now, it's only possible to set repobridge through a complete set of environment variables or through a complete config file.

While this is certainly not a huge issue, it'd be nice to have the config setup for repoSpanner and repobridge behave in a consistent way.

**Comment by puiterwijk** [comment]
So, one specific reason why the bridge isn't using Viper is because the bridge deals directly with a lot of user-provided input.
As such, I want to keep implicit behavior to a minimum, and the reason either all or none of the config comes from environment (either the calling application takes care of it or not).
I will make it so you can override just the baseurl or the CA from environment if you pass in a specific configuration value.

**Comment by puiterwijk** [comment]
@bkabrda Does this solve your issue, or would you need more?

**Comment by bkabrda** [comment]
@puiterwijk yeah, it does, thanks a lot for doing this!

**Comment by puiterwijk** [comment]
Perfect, no problem.
